---
- name: installing Multiple packages
  hosts: all
  become: true

  # vars:
  #   package_name:
  #     Ubuntu: apache2
  #     Amazon: httpd

  tasks:
    
    - name: Install packages on Ubuntu
      apt:
        name: "{{ item }}"
        state: present
      with_items:
        - nginx
        - git
        - nodejs
        - apache2
      when: ansible_distribution == 'Ubuntu'

    - name: Install packages on Amazon Linux
      yum:
        name: "{{ item }}"
        state: present
      with_items:
        - nginx
        - git
        - nodejs
        - httpd
      when: ansible_distribution == 'Amazon'
    